package io.mlpca.sonar;

import org.sonar.api.Plugin;
import org.sonar.api.config.PropertyDefinition;

public final class MlpcaPlugin implements Plugin {
  @Override
  public void define(Context context) {
    context.addExtensions(
        PropertyDefinition.builder(MlpcaSensor.REPORT_PATH_KEY)
            .name("MLPCA report path")
            .description("Path to the JSON report generated by the MLPCA analyzer.")
            .defaultValue(".mlpca/issues.json")
            .category("MLPCA")
            .build(),
        MlpcaSensor.class);
  }
}
